version: '3.8'

services:
  aider-pentest:
    build:
      context: .
      dockerfile: Dockerfile.pentest
    container_name: aider-pentesting-agent
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./audit_logs:/app/audit_logs
      - ./config:/app/config
    environment:
      - AIDER_AUTO_INSTALL=true
      - AIDER_SANDBOX_MODE=true
      - AIDER_AUDIT_ENABLED=true
      - AIDER_ZERO_TRUST=true
    networks:
      - pentest-network
    restart: unless-stopped

  # Target containers for demo
  juice-shop:
    image: bkimminich/juice-shop
    container_name: demo-juice-shop
    ports:
      - "3000:3000"
    networks:
      - pentest-network

  # Metasploitable would go here if available as container
  # metasploitable:
  #   image: metasploitable/metasploitable2
  #   container_name: demo-metasploitable
  #   ports:
  #     - "2222:22"
  #     - "8081:80"
  #   networks:
  #     - pentest-network

networks:
  pentest-network:
    driver: bridge